---
- name: RBENV setup
  hosts: new
  remote_user: joe
  become: true
  #gather_facts: true
#   https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-dkim-with-postfix-on-debian-wheezy

  tasks:
    # Variable setup.
    - name: Include OS-specific variables.
      include_vars: "../vars/{{ ansible_os_family }}.yml"

    - apt:
        update_cache: yes
        upgrade: dist

    - name: Install DKIM packages
      apt:
        name: '{{ item }}'
      with_items:
        - opendkim
        - opendkim-tools

    - blockinfile:
        path: /etc/opendkim.conf
        block: "{{ lookup('file', '../vars/dkim/opendkim.conf') }}"

    - lineinfile:
        path: /etc/opendkim.conf
        line: 'Socket                  {{ _dkim_host }}'

    - blockinfile:
        path: /etc/default/opendkim
        block: |
          SOCKET="{{ _dkim_host }}"

    - lineinfile:
        path: /etc/postfix/main.cf
        state: present
        regexp: '^milter_protocol'
        line: 'milter_protocol = 2'

    - lineinfile:
        path: /etc/postfix/main.cf
        state: present
        regexp: '^milter_default_action'
        line: 'milter_default_action = accept'

    - blockinfile:
        path: /etc/postfix/main.cf
        block: |
          smtpd_milters = {{ _dkim_milter }}
          non_smtpd_milters = {{ _dkim_milter }}

    - file:
        path: /etc/opendkim/keys
        state: directory

# Now ready to copy actual files

    - copy:
        src: '../vars/dkim/{{ item }}'
        dest: '/etc/opendkim/{{ item }}'
      with_items:
        - TrustedHosts
        - KeyTable
        - SigningTable

    - copy:
        src: '../vars/dkim/keys/{{ item.path }}'
        dest: '/etc/opendkim/keys/'
        mode: 0600
        owner: root
        group: root
      with_filetree: ../vars/dkim/keys/
      when: item.state == 'directory'

    - file:
        path: '/etc/opendkim/keys/{{ item.path }}/mail.private'
        owner: opendkim
        group: opendkim
      with_filetree: ../vars/dkim/keys/
      when: item.state == 'directory'
      notify:
        - restart postfix
        - restart opendkim

  handlers:
    - name: restart postfix
      service: name=postfix state=restarted

    - name: restart opendkim
      service: name=opendkim state=restarted


# Add/Update DKIM & SPF records in DNS
#  2check
#  sendmail check-auth@verifier.port25.com (Ctrl+D)