---
- name: Prepare app dirs and system services
  hosts: web
  remote_user: deploy
  become: true
  vars:
    server_name: dastnedast
    app_name: dastnedast
    repo: 'git@gitlab.com:aristofun/dastnedast-api.git'
    home: '/home/deploy'
    app_root: '{{ home }}/apps/dastnedast'
    logrotate_conf_dir: "/etc/logrotate.d/"
    logs_dir: '{{ app_root }}/current/log'
    gunicorn_host: "localhost:8001"
    supervisor_dir: "/etc/supervisor/conf.d/"

  tasks:
    - name: Mk app dir
      become: false
      file:
        path: '{{ app_root }}'
        state: directory

    - name: Configure passenger virtual host.
      template:
        src: ../vars/app_virtualhost.conf.j2
        dest: /etc/nginx/sites-available/{{ app_name }}.conf
      notify: restart nginx

    - name: Ensure passenger virtual host is enabled.
      file:
        src: /etc/nginx/sites-available/{{ app_name }}.conf
        dest: /etc/nginx/sites-enabled/{{ app_name }}.conf
        state: link

    - name: setup gunicorn supervisor
      template:
        src: ../vars/app_supervisor.j2
        dest: "{{ supervisor_dir }}{{ app_name }}.conf"
      notify: restart supervisor

    - name: Ensure default virtual host is removed.
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: restart nginx

    - name: add app logs to logrotate
      template:
        src: ../vars/app_logrotate.j2
        dest: "{{ logrotate_conf_dir }}{{ app_name }}.d"

  handlers:
    - name: restart supervisor
      become: true
      service: name=supervisor state=restarted

    - name: restart nginx
      become: true
      service: name=nginx state=restarted
